baseURL = 'http://localhost'
languageCode = 'en-us'
title = "Pupper Docs"
theme = "hugo-geekdoc"

pluralizeListtitles = false

# Geekdoc required
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

enableRobotsTXT = true

geekdocTagsToMenu = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
   tag = "tags"
